### PR TITLE
atf: update to latest flow protocol

### PR DESCRIPTION
**Pull request by Alex-Bair**
Updates ATF to the latest protocol changes introduced in https://github.com/estuary/flow/pull/2354.

I ran `cargo update` then fixed compilation errors from `make` to get the build to succeed locally.

### CODE REVIEW

**Review by jgraettinger — APPROVED** [review]
LGTM
